### ISSUE TITLE
Make Blog Public or Private in Admin Settings

### ISSUE THREAD

**Issue by lucasisaza** [VenusInterns/BlogTemplate#107]
Allow the owner to keep/make their blog private until they are ready to publish it to the rest of the community.

**Comment by jimmylewis** [comment]
This seems like a vague value prop.  If I wanted a completely private blog, I just wouldn't publish the site.  If I wanted the site up but didn't want to publish my posts, I would keep them all as drafts until I was ready.  Is there something I'm missing here?

**Comment by lucasisaza** [comment]
No I thought that as I was writing, but I figured I would bring it up as an issue that we could close later if we decide it doesn't bring any value.
