### ISSUE TITLE
Excerpt generator shouldn't ask us every time to feed it a maxLength

### ISSUE THREAD

**Issue by lucasisaza** [VenusInterns/BlogTemplate#122]
We should set a variable maxLength that we (the developer) can change to fit their needs but it shouldn't require all of our calls to it for us to pass in a maxLength int.

**Comment by julietdaniel** [comment]
Note to self: stop passing in "140." Make this a set variable so the developer only has to customize this in one place.

**Comment by julietdaniel** [comment]
Fixed in updated master.
