### ISSUE TITLE
Demo does not work properly

### ISSUE THREAD

**Issue by Calabonga** [VenusInterns/BlogTemplate#157]
![image](https://user-images.githubusercontent.com/346209/29855744-65cc2f8c-8d78-11e7-9a1f-300a3a2899b5.png)

This message appears when I click [Login] or [Create New Post]

**Comment by khuramshahzad** [comment]
Demo is not working. @[https://venusblog.azurewebsites.net/Account/Login?ReturnUrl=%2FNew](url)

**Comment by julietdaniel** [comment]
@Calabonga @khuramshahzad Thanks for the catch! We're working on it now.

**Comment by lucasisaza** [comment]
We had missed connecting our app to a server so it could deploy. We have since fixed that on Azure Portal and the link should be working fine now.
