### ISSUE TITLE
Excerpt is not generated after editing a post

### ISSUE THREAD

**Issue by umaslakshmi** [VenusInterns/BlogTemplate#158]
Repro:
1. Write a new post. Doesn't matter whether you write an excerpt or not.
2. Publish the post.
3. Edit the post and delete the excerpt.
4. Publish the post again.

Expected:
An excerpt is generated based on the body.

Actual:
Excerpt field is empty, as we left it after editing and publishing the post.

**Comment by julietdaniel** [comment]
Fixed in PR #159
