### ISSUE TITLE
Where do drafts go?

### ISSUE THREAD

**Issue by shanselman** [VenusInterns/BlogTemplate#25]
I made a post and clicked Save Draft. Nothing happened? Unclear from the UI if it's gone or not.

**Comment by umaslakshmi** [comment]
Yes, accessing drafts is still waiting to be implemented. If you go to our projects tab, you can see this is an item in our current sprint.

**Comment by julietdaniel** [comment]
Drafts page for accessing and editing drafts has been implemented in PR #31

**Comment by shanselman** [comment]
Fixed in #31
