### ISSUE TITLE
AccountController should be removed and replaced with a Razor Page

### ISSUE THREAD

**Issue by Eilon** [VenusInterns/BlogTemplate#41]
Currently this is the only MVC controller in the app: https://github.com/VenusInterns/BlogTemplate/blob/master/BlogTemplate/Controllers/AccountController.cs

It should probably be replaced with a Razor Page for consistency with the rest of the app.

**Comment by jimmylewis** [comment]
This we inherited from File->New Project with indiv. auth.  Maybe @haok or @blowdart can comment on why it was done this way?

**Comment by HaoK** [comment]
@danroth27 @davidfowl  I can't remember exactly the discussion you guys had around this, but I believe it was because log out doesn't return any HTML so it should be a controller...

**Comment by davidfowl** [comment]
We did this on purpose since it was just code without a razor view.

**Comment by Eilon** [comment]
@davidfowl for real? That's super bizarre.

**Comment by davidfowl** [comment]
Why is that bizzare? Razor pages are optimized for pages. Nothing else. I think it also shows the fact that you can mix them. There's no need to be "completely razor pages" or "completely views" , everybody wins

**Comment by Eilon** [comment]
It's bizarre to me that we "shouldn't" use Razor Pages unless there's HTML being rendered. Is it difficult or awkward or bizarre to write https://github.com/VenusInterns/BlogTemplate/blob/master/BlogTemplate/Controllers/AccountController.cs in Razor Pages? I believe it would be a lot less awkward to do it in Razor Pages because you could do it with.... yup, that's right, "a lot less ceremony"!

Honestly it mostly looks odd to me because it looks like it was just an accident or oversight.

**Comment by davidfowl** [comment]
If it had 2 actions, would it still look weird?

**Comment by jimmylewis** [comment]
@davidfowl @danroth27 Would it be so weird to have a Razor Page with no markup and just a couple handlers?  E.g. https://github.com/VenusInterns/BlogTemplate/blob/master/BlogTemplate/Pages/ManageComment.cshtml.cs

I also wouldn't expect to use Pages to write a WebAPI, but I would expect that I shouldn't have to learn MVC concepts to write a website with Pages.

**Comment by davidfowl** [comment]
@jimmylewis That page has view associated with it. What's we talking about here is "logic" only pages. Which feel a bit like a hack since nothing is being rendered.

**Comment by Eilon** [comment]
Closing because this isn't that big a deal 😄
