### ISSUE TITLE
Slug list should use an allow-list instead of an exclude-list of replacement chars

### ISSUE THREAD

**Issue by Eilon** [VenusInterns/BlogTemplate#43]
The slug generator currently replaces only a space (` `) with a dash (`-`). It is more typical for a slug generator to have a limited set of allowed characters (e.g. alpha chars, numbers, etc.) and replace all other chars with a replacement char (dash is fine).

See https://github.com/VenusInterns/BlogTemplate/blob/master/BlogTemplate/Services/SlugGenerator.cs#L20

**Comment by Eilon** [comment]
I looked at it a bit more, and I think this is especially important because slugs appear in URLs, such as in https://github.com/VenusInterns/BlogTemplate/blob/master/BlogTemplate/Pages/ManageComment.cshtml.cs#L31.

Given that, using a known-safe list of chars in slugs seems like a good idea.

**Comment by julietdaniel** [comment]
Is it okay if we use Path.GetInvalidFileNameChars(), an exclude-list approach to replace invalid file name characters in the slug, as we've done in https://github.com/VenusInterns/BlogTemplate/pull/53/files#diff-262035e5051e9cfcefefc9277addb4a5 (see line 23)? This takes care of <, >, :, *, ?, \\, and /, as well as some others (41 characters total).

If not, I can just use a known-safe list of chars instead. Thanks!

**Comment by Eilon** [comment]
I don't recommend using `Path.GetInvalidFileNameChars()` because that's for filesystem paths, not URLs. I suggest creating your own known-safe list of chars. (The nice thing is that you can start with a conservative list, and you can always *safely* add more safe chars to your list, but it's much harder to remove items if you have too many!)

**Comment by julietdaniel** [comment]
See PR #84 . Here we use an allow-list approach by using regex.
