### ISSUE TITLE
Recommend fields set by ctor that are immutable be marked as 'readonly'

### ISSUE THREAD

**Issue by Eilon** [VenusInterns/BlogTemplate#44]
E.g. see https://github.com/VenusInterns/BlogTemplate/blob/master/BlogTemplate/Services/SlugGenerator.cs#L11

This code:

```c#
        private BlogDataStore _dataStore;
```

Should be:

```c#
        private readonly BlogDataStore _dataStore;
```

This ensures that the `_dataStore` field can't be overwritten anywhere else. The `readonly` modifier indicates that the field can be set from only the constructor.

I recommend checking elsewhere in the code in case this same recommendation applies anywhere else.

**Comment by lucasisaza** [comment]
Fixed in PR #80
