### ISSUE TITLE
The SlugGenerator isn't really a "service"

### ISSUE THREAD

**Issue by Eilon** [VenusInterns/BlogTemplate#45]
The SlugGenerator is new'ed up wherever it's used, e.g.:

1. https://github.com/VenusInterns/BlogTemplate/blob/007603b096e1cdc563f83b5fddce5bbcf9ce5f4f/BlogTemplate/Pages/New.cshtml.cs#L60
2. https://github.com/VenusInterns/BlogTemplate/blob/fb4d281cfd8c6b6a09fd35e8f21bf037072c41de/BlogTemplate/Pages/Edit.cshtml.cs#L78

It would be more typical to register the SlugGenerator as an actual service in Startup.cs's ConfigureService method, and then consume it from the DI container wherever it's used.

If you haven't used this pattern before, your friendly local Ryan (e.g. @rynowak) or Taylor (@NTaylorMullen) can help you do this in Razor Pages.

**Comment by lucasisaza** [comment]
Also for Excerpt Generation.

**Comment by julietdaniel** [comment]
See PR #70
