### ISSUE TITLE
Can't post new blog entry unless you first go to the /Index page to "load" the blog posts

### ISSUE THREAD

**Issue by Eilon** [VenusInterns/BlogTemplate#49]
I haven't actually tried it, but I'm certain it will happen:

1. Launch the site, but *do not* visit the `/` (or `/Index`) page!
2. Browse to the `/New` page and type in your awesome new blog post
3. Press the Save button (doesn't matter whether it's Public or Draft)

Result: I'm guessing that this line will throw a null ref exception: https://github.com/VenusInterns/BlogTemplate/blob/78322d7dd8eb511b55590fa803ce7a54fe34e7f4/BlogTemplate/Pages/New.cshtml.cs#L70

Why? Because the only thing that seems to "load" the blog posts is the `/Index` page here: https://github.com/VenusInterns/BlogTemplate/blob/c122697f44b6e97105bbc6b9c3decd9456f26aa5/BlogTemplate/Pages/Index.cshtml.cs#L30

While this bug is trivial to fix, I think there's a bit of a mismatch between how the singleton `Blog` service is used, and how the `IDataStore` is used. It isn't clear from the code what is the responsibility of each - in fact, it seems like they both *share* certain responsibilities, which is apparent in [this code](https://github.com/VenusInterns/BlogTemplate/blob/78322d7dd8eb511b55590fa803ce7a54fe34e7f4/BlogTemplate/Pages/New.cshtml.cs#L69-L70), where when a new post is added, two different data structures need to be modified. (This is also orthogonally related to https://github.com/VenusInterns/BlogTemplate/issues/47.)

I'm happy to discuss this in person if anything here wasn't clear.

**Comment by jimmylewis** [comment]
No longer an issue since we got rid of the Blog class.
