### ISSUE TITLE
Slug Generator Test

### ISSUE THREAD

**Issue by umaslakshmi** [VenusInterns/BlogTemplate#79]
The test for SlugGenerator about removing invalid characters in the title is failing.

**Comment by julietdaniel** [comment]
We might want to address this after we implement the allow-list approach for slug generation. Currently we're using a disallow-list approach.

**Comment by julietdaniel** [comment]
See related issue #43

**Comment by julietdaniel** [comment]
Test passes in PR #84 , where I've edited the CreateSlug method (used regular expressions and reordered some logic).
