### ISSUE TITLE
Need to support formatting in some way... any way

### ISSUE THREAD

**Issue by jimmylewis** [VenusInterns/BlogTemplate#87]
Repro:
1. Create a new post
2. Write a post with multiple paragraphs
3. Publish and view post

Expected:
Paragraph breaks are preserved when rendered.

Actual:
It's just a single glob of text.

**Comment by lucasisaza** [comment]
Make sure to disallow html markup in markdown library.

**Comment by julietdaniel** [comment]
Addressed in PR #155 and disallowed HTML markup in markdown library.
