### ISSUE TITLE
Characters not accepted as the title

### ISSUE THREAD

**Issue by lucasisaza** [VenusInterns/BlogTemplate#91]
The following characters alone or repeated 'break' the slug so that once you publish or save the draft, you cannot access it since the character title seems to break the slug. Those characters are: '#', '/', '\', '|', '<', '>'

Similarly, if the title of the post is '%' then we get a BadRequest 400 error 'Invalid URL'.

**Comment by jimmylewis** [comment]
This should be covered by #84

**Comment by julietdaniel** [comment]
Yes, this is covered by #84, which has already been merged. PR #113 confirms that tests pass for removing '#', '/', '', '|', '<', '>', '%' and other invalid characters from the title. The allow-list approach will use 63 valid characters to generate a slug.
