### ISSUE TITLE
Cancel Button looses purpose

### ISSUE THREAD

**Issue by lucasisaza** [VenusInterns/BlogTemplate#94]
When the logged in user goes to drafts and selects a draft he/she is taken to the edit page of that post. However, there is a small cancel button at the bottom that when pressed just takes you back to the previous page. I think this button may not be necessary in this scenario since you could just use the arrows to go back.

**Comment by jimmylewis** [comment]
I disagree.  I think it's useful to have a UI even if there's another way to accomplish the same gesture.  Also, sometimes the back buttons on the browser are harder to get to (e.g. if you're using a phone).
